version: '3.1'

services:
  cassandra-node-1:
    image: cassandra:latest
    ports:
      - 9042:9042
  cassandra-node-2:
    image: cassandra:latest
    environment:
      CASSANDRA_SEEDS: cassandra-node-1
  cassandra-node-3:
    image: cassandra:latest
    environment:
      CASSANDRA_SEEDS: cassandra-node-1
